version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: bookstore-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: bookstore
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - bookstore-network

  redis:
    image: redis:7.2-alpine
    container_name: bookstore-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - bookstore-network

  app:
    build: .
    container_name: bookstore-catalog
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/bookstore?authSource=admin
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
      - redis
    networks:
      - bookstore-network

volumes:
  mongodb_data:
  redis_data:

networks:
  bookstore-network:
    driver: bridge