spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/bookstore"
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  servlet:
    context-path: /wise-man-bookstore-catalog/

